CREATE TABLE cuatrimestres (
id_cuatrimestre int AUTO_INCREMENT PRIMARY KEY,
nombre_cuatri VARCHAR(255) NOT NULL
);

CREATE TABLE materias (
  id_materia int AUTO_INCREMENT PRIMARY KEY,
  nombre_materia VARCHAR(255) NOT NULL
);

CREATE TABLE roles (
id_rol int AUTO_INCREMENT PRIMARY KEY,
nombre_rol VARCHAR (255) NOT NULL
);

CREATE TABLE cursos (
id_curso int AUTO_INCREMENT PRIMARY KEY,
nombre_cursos VARCHAR(255) NOT NULL
);


CREATE TABLE alumnos (
id_alumno int AUTO_INCREMENT PRIMARY KEY,
nombre_alumno VARCHAR(255) NOT NULL,
apellido_alumno VARCHAR(255) NOT NULL,
curso int,
FOREIGN KEY (curso) references cursos(id_curso)
);

CREATE TABLE materia_alumno(
id_alumno_materia int AUTO_INCREMENT PRIMARY KEY,
alumno int NOT NULL,
materia int NOT NULL,
foreign key (alumno) references alumnos(id_alumno),
foreign key (materia) references materias(id_materia)
);

CREATE TABLE profesores(
id_profesor int AUTO_INCREMENT PRIMARY KEY,
nombre_profesor VARCHAR(255) NOT NULL,
apellido_profesor VARCHAR(255) NOT NULL,
materia int,
foreign key(materia) references materias(id_materia)
);

CREATE TABLE usuarios(
id_usuarios int AUTO_INCREMENT PRIMARY KEY,
nombre_usuario VARCHAR(255) NOT NULL,
apellido_usuario VARCHAR(255) NOT NULL,
rol int,
foreign key(rol) references roles(id_rol)
);

CREATE TABLE notas_informe (
  id_informe int AUTO_INCREMENT PRIMARY KEY,
  año VARCHAR(5) NOT NULL,
nota float NOT NULL,
profesor int NOT NULL,
alumno int NOT NULL,
cuatrimestre int NOT NULL,
materia int NOT NULL,
curso int NOT NULL,
foreign key (profesor) references profesores(id_profesor),
foreign key (alumno) references alumnos(id_alumno),
foreign key(cuatrimestre) references cuatrimestres(id_cuatrimestre),
foreign key(materia) references materias(id_materia),
foreign key(curso) references cursos(id_curso)
);

INSERT INTO cursos VALUES
(default,'Primero A'),
(default,'Segundo A' ),
(default,'Tercero A'),
(default,'Cuarto A'),
(default,'Quinto A');


INSERT INTO materias VALUES
(default,'Matematicas'),
(default,'Ingles' ),
(default,'Quimica'),
(default,'Fisica'),
(default,'Música'),
(default,'Historia'),
(default,'Biología');


INSERT INTO roles VALUES
(default,'Administrador'),
(default,'Secretaria' ),
(default,'Profesor');




INSERT INTO profesores VALUES
(default,'Juan','Perez',1),
(default,'Pedro','Gomez',2),
(default,'Juana','Fernandez',3),
(default,'Lucía','Galán',4),
(default,'Julio','Iglesias',5),
(default,'Teresa','Gutierrez',6),
(default,'Alberto','Gonzalez',7);

INSERT INTO cuatrimestres VALUES
(default,'Primer Cuatrimestre'),
(default,'Segundo Cuatrimestre');

INSERT INTO alumnos VALUES
(default,'Carolina','Marquesin',1),
(default,'Juan','Ruarte',1),
(default,'Matias','Carrizo',1),
(default,'Hernan','Redondo',1),
(default,'Waldo','Velasquez',1),
(default,'Sergio','Armas',2),
(default,'Miguel','Juarez',2),
(default,'Lucas','Fiore',2),
(default,'Adriana','Gonzalez',2),
(default,'Vanesa','Veron',2),
(default,'Maria','Duarte',2),
(default,'Maira','Narvaez',3),
(default,'Teresa','Guillen',3),
(default,'Martin','San',3),
(default,'Nestor','Gomez',3),
(default,'Cabrera','Gavilan',3),
(default,'Enrique','Kracher',3),
(default,'Miguel','Barrios',4),
(default,'Sandra','Romero',4),
(default,'Micaela','Michela',4),
(default,'Carlos','Gonzalez',4),
(default,'Oscar','Carvajal',4),
(default,'Luciano','Dugour',4),
(default,'Cintia','Insaurralde',5),
(default,'Javier','Dauo',5),
(default,'Rossi','Planes',5),
(default,'Gustavo','Schamne',5),
(default,'Gustavo','Benitez',5),
(default,'Elizabeth','Beron',5);

INSERT INTO materia_alumno VALUES
(default,1,1),
(default,1,2),
(default,1,3),
(default,1,4),
(default,1,5),
(default,1,6),
(default,1,7),
(default,2,1),
(default,2,2),
(default,2,3),
(default,2,4),
(default,2,5),
(default,2,6),
(default,2,7),
(default,3,1),
(default,3,2),
(default,3,3),
(default,3,4),
(default,3,5),
(default,3,6),
(default,3,7),
(default,4,1),
(default,4,2),
(default,4,3),
(default,4,4),
(default,4,5),
(default,4,6),
(default,4,7),
(default,5,1),
(default,5,2),
(default,5,3),
(default,5,4),
(default,5,5),
(default,5,6),
(default,5,7),
(default,6,1),
(default,6,2),
(default,6,3),
(default,6,4),
(default,6,5),
(default,6,6),
(default,6,7),
(default,7,1),
(default,7,2),
(default,7,3),
(default,7,4),
(default,7,5),
(default,7,6),
(default,7,7),
(default,8,1),
(default,8,2),
(default,8,3),
(default,8,4),
(default,8,5),
(default,8,6),
(default,8,7),
(default,9,1),
(default,9,2),
(default,9,3),
(default,9,4),
(default,9,5),
(default,9,6),
(default,9,7),
(default,10,1),
(default,10,2),
(default,10,3),
(default,10,4),
(default,10,5),
(default,10,6),
(default,10,7),
(default,11,1),
(default,11,2),
(default,11,3),
(default,11,4),
(default,11,5),
(default,11,6),
(default,11,7),
(default,12,1),
(default,12,2),
(default,12,3),
(default,12,4),
(default,12,5),
(default,12,6),
(default,12,7),
(default,13,1),
(default,13,2),
(default,13,3),
(default,13,4),
(default,13,5),
(default,13,6),
(default,13,7),
(default,14,1),
(default,14,2),
(default,14,3),
(default,14,4),
(default,14,5),
(default,14,6),
(default,14,7),
(default,15,1),
(default,15,2),
(default,15,3),
(default,15,4),
(default,15,5),
(default,15,6),
(default,15,7),
(default,16,1),
(default,16,2),
(default,16,3),
(default,16,4),
(default,16,5),
(default,16,6),
(default,16,7),
(default,17,1),
(default,17,2),
(default,17,3),
(default,17,4),
(default,17,5),
(default,17,6),
(default,17,7),
(default,18,1),
(default,18,2),
(default,18,3),
(default,18,4),
(default,18,5),
(default,18,6),
(default,18,7),
(default,19,1),
(default,19,2),
(default,19,3),
(default,19,4),
(default,19,5),
(default,19,6),
(default,19,7),
(default,20,1),
(default,20,2),
(default,20,3),
(default,20,4),
(default,20,5),
(default,20,6),
(default,20,7),
(default,21,1),
(default,21,2),
(default,21,3),
(default,21,4),
(default,21,5),
(default,21,6),
(default,21,7),
(default,22,1),
(default,22,2),
(default,22,3),
(default,22,4),
(default,22,5),
(default,22,6),
(default,22,7),
(default,23,1),
(default,23,2),
(default,23,3),
(default,23,4),
(default,23,5),
(default,23,6),
(default,23,7),
(default,24,1),
(default,24,2),
(default,24,3),
(default,24,4),
(default,24,5),
(default,24,6),
(default,24,7),
(default,25,1),
(default,25,2),
(default,25,3),
(default,25,4),
(default,25,5),
(default,25,6),
(default,25,7),
(default,26,1),
(default,26,2),
(default,26,3),
(default,26,4),
(default,26,5),
(default,26,6),
(default,26,7),
(default,27,1),
(default,27,2),
(default,27,3),
(default,27,4),
(default,27,5),
(default,27,6),
(default,27,7),
(default,28,1),
(default,28,2),
(default,28,3),
(default,28,4),
(default,28,5),
(default,28,6),
(default,28,7),
(default,29,1),
(default,29,2),
(default,29,3),
(default,29,4),
(default,29,5),
(default,29,6),
(default,29,7);
